In [64]:
import numpy as np
import pandas as pd
import os
import sys
import math
from sklearn.svm import SVR
from sklearn import preprocessing as pp
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [65]:
#Import Data
os.chdir('C:\Users\senth\Desktop\Files_Desktop_access')
Master_Data = pd.read_csv('Dummy_Data.csv').dropna()
list(Master_Data)

['X', 'Y', 'Theta', 'Cos_Theta', 'Sin_Theta', 'Z']

In [66]:
# Input and output columns in Dataframe
Input = ['X','Y','Cos_Theta','Sin_Theta']
Output = 'Z'

In [67]:
# Name Input and target values
X = Master_Data[Input].values
y = Master_Data[Output].values

In [68]:
X = (X-X.min())/(X.max()-X.min())

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [70]:
# Fit regression model
svr_rbf = SVR(C=0.0263665089873, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma=1, kernel='rbf', max_iter=1, shrinking=True, tol=0.001,
  verbose=False)
svr_poly = SVR(kernel='poly', C=1e-13, degree=80)

In [71]:
svr_poly.fit(X_train,y_train)

SVR(C=1e-13, cache_size=200, coef0=0.0, degree=80, epsilon=0.1, gamma='auto',
  kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [72]:
y_predicted = svr_poly.predict(X_test)

In [73]:
y_test

array([  252.1783483 ,   441.        ,  1135.462529  , -3198.382385  ,
        1654.665997  ,   256.        ,   121.        ,    28.15121734,
         565.7667965 ,  2452.283822  ,   676.        ])

In [74]:
y_predicted

array([ 87.56192649,  87.56192649,  87.56192649,  87.56192649,
        87.56192649,  87.56192649,  87.56192649,  87.56192649,
        87.56192649,  87.56192649,  87.56192649])

In [75]:
scores_mse = cross_val_score(svr_poly, X, y, scoring='neg_mean_absolute_error',cv=10)
scores_mse

array([ -256.17389033,  -143.2510341 ,  -281.29214211,  -366.74363911,
        -852.43389453, -1184.36176117,  -962.59899045, -2777.01325112,
       -1597.40770727, -2654.02293905])

In [76]:
scores_r2 = cross_val_score(svr_poly, X, y, scoring='r2',cv=10)
scores_r2

array([ -5.60989687e+01,  -2.64596059e+00,  -9.97563804e-02,
        -1.23612419e-01,  -8.66733695e-04,  -3.44239838e+00,
        -2.64431178e-01,  -3.56452880e-02,  -9.52900749e-01,
        -1.54847124e-02])

In [77]:
scores_r2.max()

-0.00086673369490619656

In [78]:
min_val = Master_Data[Output].min()
max_val = Master_Data[Output].max()
ran = max_val - min_val

In [79]:
rscores_mse = -1*scores_mse
rscores_mse = rscores_mse*ran

In [80]:
rscores_mse

array([  2156876.60961386,   1206113.56743287,   2368361.74447805,
         3087827.47497058,   7177135.5231029 ,   9971828.81026876,
         8104679.38128083,  23381285.72869925,  13449502.27148167,
        22345758.93489073])

In [81]:
A = range(1,11)

In [82]:
x = A
y1 = (rscores_mse)

plt.plot(x, y1,'b-')
plt.xlabel('Iteration',size = 15)
plt.ylabel('Mean Absolute Error (Gpa)', size = 15)
plt.title('Support Vector Regression')
plt.show()


In [83]:
# os.chdir('E:\Academics\Research\Data\Experimental data\Compression_test\Analysis\Combo_validation')
# fig1.savefig('SVR_Cross_validation.jpeg')

In [84]:
y_test = y_test*ran +min_val
y_predicted = y_predicted*ran+min_val

In [85]:
fig2 = plt.figure(figsize=(16,9))
ax = fig2.add_subplot(111)
ax.plot(y_test,y_predicted,'.',markersize = 20)
ax.set_xlabel('Actual')
ax.set_ylabel('Predicted')
xlim = ax.get_xlim()
ylim = ax.get_ylim()
ax.plot(y_test, y_test, 'k--')
plt.show()